[metadata]
name = sasci360solutions
version = 0.0.1
author = Mark Nelson
author_email = Mark.Nelson@sas.com
description = An awesome package that does something
long_description = file: README.md
long_description_content_type = text/markdown
url = https://gitlab.sas.com/psd-ci-enablement/sas_ci360_solutions
project_urls = Bug Tracker = https://gitlab.sas.com/psd-ci-enablement/sas_ci360_solutions/issues
classifiers = Programming Language :: Python :: 3
              License :: OSI Approved :: MIT License
              Operating System :: OS Independent

[install_requires]
package = cryptography
          matplotlib
          numpy
          packaging
          pandas
          PyJWT
          python-daemon
          python-dateutil
          query-string
          requests
          rsa
          sas-dlpy
          sas-esppy
          SAS-kernel
          saspy
          schedule
          urllib3

[options]
package_dir = = src
packages = find:
python_requires = >=3.6

[options.packages.find]
where = src
